[project]
name = "senbac-team"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pydub>=0.25.1",
    "uvicorn>=0.34.0",
    "websockets>=15.0.1",
]
